apiVersion: apps/v1
kind: Deployement
metadata:
  name: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
       app: python
    spec:
      containers:
     - name: python
       image: <dockerhub-username>/devops-python-app:latest
       ports:
       - containerPort: 5000
